name: Build containers

on:
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - name: Try to build docker containers
       - uses: actions/checkout@v2

       - run: |
           docker-compose build