name: Publish containers

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

       - run: echo $CR_PAT | docker login ghcr.io -u pr0tex --password-stdin
         env:
           CR_PAT: ${{ secrets.CR_PAT }}
       - run: |
           docker-compose build
           docker-compose push